Parameters:
  VpcId:
    Description: ID of an existing VPC.
    Type: "AWS::EC2::VPC::Id" # During the deployment you will select the VPC of your choice
  PublicSubnetId:
    Description: ID of an existing public subnet within the specified VPC.
    Type: "AWS::EC2::Subnet::Id" # During the deployment you will select the Subnet of your choice
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance.
    Type: "AWS::EC2::KeyPair::KeyName"
  SSMParamaterWindowAMIId:
    Description: Name of a Parameter Store parameter where the instance ID is located.
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-windows-latest/EC2LaunchV2-Windows_Server-2016-English-Full-Base"

  InstanceTypeParameter:
    Description: Webserver Instance Type can be t2.micro, m1.small, or m1.large. Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.medium
      - t3.large
      - m1.small
      - m1.large
      - m2.2xlarge
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 3389 - RDP protocol
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 3389
          ToPort: 3389
          CidrIp: 0.0.0.0/0

  WindowEc2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref SSMParamaterWindowAMIId
      InstanceType: !Ref InstanceTypeParameter
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !Ref PublicSubnetId
          GroupSet:
            - !Ref InstanceSecurityGroup
      Tags:
        - Key: "Name"
          Value: "Benwebserver"
        - Key: "Department"
          Value: "Finance"
